services:
  - type: web
    name: edwisely-assessment
    runtime: python
    plan: free
    startCommand: gunicorn wsgi:app
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
